### ISSUE TITLE
Have i to compile opewrt to install aprx?

### ISSUE THREAD

**Issue by ducarpit** [chazapis/openwrt-aprx#2]
Hi,
i am trying to install aprs on my openwrt. But i don't understand how....Havi i to build openwrt first on a LInux VM? Because i have installed it without compile it.....
Sorry but i am a beginner....
Thank a lot...

**Comment by chazapis** [comment]
Hi. Assuming you are running OpenWrt 15.05 on the ar71xx architecture, you can install one of the already compiled packages, found in [releases](https://github.com/chazapis/openwrt-aprx/releases).

Otherwise, yes - you need a Linux VM and a process to compile your own package. It definitely is not a task for a beginner... You can check the following links for info:
* https://wiki.openwrt.org/about/toolchain
* https://wiki.openwrt.org/doc/howtobuild/single.package
* https://github.com/OnionIoT/OpenWRT-Packages/wiki/Setting-Up-the-Cross-Compile-Environment
